base_url: "https://terrafirmagreg.api.crowdin.com"
base_path: "../../shaders"

project_id_env: "CROWDIN_ID"
api_token_env: "CROWDIN_TOKEN"

preserve_hierarchy: true

files:
  - source: "/lang/en_us.lang"
    translation: "/%original_path%/%locale_with_underscore%.%file_extension%"
    type: "properties"
    update_option: "update_as_unapproved"

    # languages_mapping:
    #   locale_with_underscore:
        # en-US: "en_us"
        # zh-CN: "zh_cn"
        # ja-JP: "ja_jp"
        # pl-PL: "pl_pl"
        # pt-BR: "pt_br"
        # ru-RU: "ru_ru"
        # uk-UA: "uk_ua"
        # en-GB: "en_gb"
        # zh-CN: "zh_cn"
        # zh-TW: "zh_tw"
        # es-ES: "es_es"
        # pt-PT: "pt_pt"
        # sv-SE: "sv_se"
        # en: "en_us"
        # de: "de_de"
        # fr: "fr_fr"
        # it: "it_it"
        # ar: "ar_sa"
        # hu: "hu_hu"
        # fi: "fi_fi"
        # ro: "ro_ro"
        # ca: "ca_es"
        # da: "da_dk"
        # el: "el_gr"
        # cs: "cs_cz"
        # he: "he_il"
        # ko: "ko_kr"
        # nl: "nl_nl"
        # pl: "pl_pl"
        # sr: "sr_sp"
        # tr: "tr_tr"
        # vi: "vi_vn"
