### Last updated: February 05, 2026, 11:02 UTC
# Copyright (c) 2026 SpacEagle17 – Licensed under the MIT License: https://opensource.org/licenses/MIT
#---------------------------------------------------------------------------------------------------------------------
##### IMPORTANT! WHERE TO CONTRIBUTE: #####
# If you want to contribute to the Euphoria Patches modded support library, please only edit the files from GitHub. https://euphoriapatches.com/properties
#
#---------------------------------------------------------------------------------------------------------------------

dimension.world_overworld=*
dimension.world_beneath=minecraft:the_nether
dimension.world_europa=ad_astra:glacio
dimension.world_mars=ad_astra:mars
dimension.world_mercury=ad_astra:mercury
dimension.world_moon=ad_astra:moon
dimension.world_orbit=ad_astra:moon_orbit ad_astra:mercury_orbit ad_astra:mars_orbit ad_astra:glacio_orbit ad_astra:venus_orbit ad_astra:earth_orbit
dimension.world_venus=ad_astra:venus